// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msxrlfycyuimzymtowob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zeHJsZnljeXVpbXp5bXRvd29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjg3NTcsImV4cCI6MjA2NTkwNDc1N30.8BpxPsUP7Ge3HhM0IBCyEu63ylgEjlBR5t0THL3HNAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);